import { Category, Settings, Tool } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'AI', slug: 'ai', icon: 'Sparkles', description: 'Web-based Artificial Intelligence tools and copilots' },
  { id: 'cat-2', name: 'PDF', slug: 'pdf', icon: 'FileText', description: 'Document processing and PDF web software' },
  { id: 'cat-3', name: 'Image', slug: 'image', icon: 'Image', description: 'Browser-based graphic, icon, and photo utilities' },
  { id: 'cat-4', name: 'Developer', slug: 'developer', icon: 'Code', description: 'Developer tools, API formatters, and code helpers' },
  { id: 'cat-5', name: 'Student', slug: 'student', icon: 'GraduationCap', description: 'Study aids, calculators, and research tools' },
  { id: 'cat-6', name: 'Business', slug: 'business', icon: 'Briefcase', description: 'Invoicing, CRM, and productivity Micro SaaS' },
  { id: 'cat-7', name: 'Utilities', slug: 'utilities', icon: 'Wrench', description: 'Handy online web utilities and converters' },
  { id: 'cat-8', name: 'Apps', slug: 'apps', icon: 'LayoutGrid', description: 'Web applications and standalone web suites' },
];

export const INITIAL_SETTINGS: Settings = {
  website_name: 'Toolly',
  logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
  favicon: '/favicon.ico',
  tagline: 'Every Tool in One Place.',
  footer_text: '© 2026 Toolly Platform. All independent Micro SaaS rights reserved.',
  social_links: {
    twitter: 'https://twitter.com/toolly',
    github: 'https://github.com/toolly',
    discord: 'https://discord.gg/toolly',
  },
  analytics_id: 'UA-TOOLLY-2026',
};

// Default starts EMPTY as requested ("All sections should show 'No tools available yet'")
export const INITIAL_TOOLS: Tool[] = [];

// Realistic Sample Tools that can be seeded via Admin Panel with 1 click
export const DEMO_SAMPLE_TOOLS: Tool[] = [
  {
    id: 'tool-1',
    name: 'DocuMind AI',
    slug: 'documind-ai',
    description: 'Instant document Q&A and summary engine for web workflows.',
    full_description: 'DocuMind AI parses PDFs, text documents, and web links to instantly answer questions and extract critical insights directly in your browser.',
    icon: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    website_url: 'https://documind.example.com',
    apk_url: 'https://documind.example.com/app.apk',
    category_id: 'cat-1',
    featured: true,
    popular: true,
    new: true,
    status: 'published',
    seo_title: 'DocuMind AI - Document Summarizer',
    seo_description: 'Instant document summaries and search powered by AI.',
    keywords: 'ai, doc, summary, pdf',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'tool-2',
    name: 'PixelForge Studio',
    slug: 'pixelforge-studio',
    description: 'Lightning fast SVG & icon optimizer for modern designers.',
    full_description: 'Compress, format, and generate crisp vector graphic code on the fly without server uploads.',
    icon: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=150&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    website_url: 'https://pixelforge.example.com',
    category_id: 'cat-3',
    featured: true,
    popular: true,
    new: false,
    status: 'published',
    seo_title: 'PixelForge Studio - Vector & Graphic Utility',
    seo_description: 'Browser-based SVG and icon compiler.',
    keywords: 'image, svg, graphics, designer',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'tool-3',
    name: 'DevPulse API Tester',
    slug: 'devpulse-api-tester',
    description: 'Zero-latency browser REST and GraphQL request workbench.',
    full_description: 'Test API endpoints, inspect headers, mock payloads, and export curl snippets seamlessly.',
    icon: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=150&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    website_url: 'https://devpulse.example.com',
    category_id: 'cat-4',
    featured: false,
    popular: true,
    new: true,
    status: 'published',
    seo_title: 'DevPulse API Workbench',
    seo_description: 'Fast, minimal API testing environment.',
    keywords: 'developer, api, rest, testing',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'tool-4',
    name: 'Invoicer Pro',
    slug: 'invoicer-pro',
    description: 'Minimalist invoice & receipt compiler for freelancers.',
    full_description: 'Generate beautiful PDF invoices in seconds with custom tax, currency, and multi-client settings.',
    icon: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=150&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
    website_url: 'https://invoicer.example.com',
    apk_url: 'https://invoicer.example.com/download.apk',
    category_id: 'cat-6',
    featured: true,
    popular: false,
    new: true,
    status: 'published',
    seo_title: 'Invoicer Pro - Micro SaaS Invoicing',
    seo_description: 'Instant PDF invoices for modern independents.',
    keywords: 'business, invoice, finance, pdf',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'tool-5',
    name: 'PDF Merge & Compress',
    slug: 'pdf-merge-compress',
    description: 'Combine, reorder, and shrink PDF files client-side.',
    full_description: 'Privacy-focused browser PDF tool suite that operates without uploading your sensitive files.',
    icon: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=150&auto=format&fit=crop&q=80',
    category_id: 'cat-2',
    website_url: 'https://pdfmerge.example.com',
    featured: false,
    popular: true,
    new: false,
    status: 'published',
    seo_title: 'PDF Merge & Compress Tool',
    seo_description: 'Client-side PDF management.',
    keywords: 'pdf, merge, compress, document',
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'tool-6',
    name: 'GradeFlow Planner',
    slug: 'gradeflow-planner',
    description: 'GPA calculator, course tracker, and assignment scheduler.',
    full_description: 'Streamlined academic workspace built for high school and university students.',
    icon: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=150&auto=format&fit=crop&q=80',
    website_url: 'https://gradeflow.example.com',
    category_id: 'cat-5',
    featured: true,
    popular: false,
    new: true,
    status: 'published',
    seo_title: 'GradeFlow Planner - Student Academic Tool',
    seo_description: 'Smart academic tracking and GPA utility.',
    keywords: 'student, gpa, schedule, study',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
];
